### ISSUE TITLE
Issue with readme

### ISSUE THREAD

**Issue by thatpumpkin** [veasman/x352#1]
I see "gamesneeze" is this an error? Cuz I don't enjoy the company of weebs.

**Comment by veasman** [comment]
There seems to be an issue with our new employee. We will be launching an investigation into this.

**Comment by thatpumpkin** [comment]
Im a necroposter :zombie:

**Comment by veasman** [comment]
stfu....

**Comment by veasman** [comment]
wait no i meant to close it how tf did you comment???
